GENERAL_TTS:
  TTS_PROVIDER: "azure"  # Possible values: "openai", "azure"

PROCESSING_PIPELINE:
  # === Segmentation Settings ===
  USE_PHRASE_SEGMENTATION: false # (global setting) Set to false to turn off segmentation during streaming
  DELIMITERS: [". ", "? ", "! "]  # Delimiters used for segmentation
  MINIMUM_PHRASE_LENGTH: 25  # Minimum length before attempting segmentation

  # === Modules to Include ===
  MODULES:
   - segmentation
 #  - tokenizer
 #   - custom_text_modifier

  # === Tokenizer Settings ===
  TOKENIZER:
    TYPE: "stanza"  # Options: "nltk", "stanza", "none"

    # --- NLTK Tokenizer Options ---
    NLTK:
      LANGUAGE: "english"  # Language for NLTK tokenizer (e.g., "english", "spanish")
      TOKENIZER: "word_tokenize"  # Tokenizer to use: "word_tokenize", "TreebankWordTokenizer", "TweetTokenizer"
      PRESERVE_LINE: false  # Whether to preserve line breaks (only applicable for "word_tokenize")

    # --- Stanza Tokenizer Options ---
    STANZA:
      LANGUAGE: "en"  # Language code for Stanza tokenizer (e.g., "en", "es")
      PROCESSORS: "tokenize"  # Processors to use, comma-separated (e.g., "tokenize,pos,lemma")
      TOKENIZE_NO_SSPLIT: false  # Set to true to disable sentence splitting
      USE_GPU: false  # Whether to use GPU for processing
      VERBOSE: false  # Whether to output verbose logs

  # === Custom Text Modifier Settings ===
  CUSTOM_TEXT_MODIFIER:
    ENABLED: false  # Set to true to enable custom text modification

TTS_MODELS:
  # OpenAI TTS Configuration
  OPENAI_TTS:
    TTS_CHUNK_SIZE: 1024
    TTS_SPEED: 1.0  # Possible values: 0.5 (slower) to 2.0 (faster); 1.0 is standard speed
    TTS_VOICE: "alloy"  # Possible values: alloy, echo, fable, onyx, nova, and shimmer
    TTS_MODEL: "tts-1"  # Possible values: model-specific, e.g., "tts-1", "tts-2"
    AUDIO_RESPONSE_FORMAT: "pcm"  # Possible values: "pcm" (default), "mp3", "wav"; audio encoding formats
    AUDIO_FORMAT_RATES:
      pcm: 24000  # Sample rate for PCM audio
      mp3: 44100  # Sample rate for MP3 audio
      wav: 48000  # Sample rate for WAV audio
    PLAYBACK_RATE: 24000  # Default sample rate for OpenAI audio playback

  # Azure TTS Configuration
  AZURE_TTS:
    TTS_SPEED: "0%"  # Can be percentage or numerical value; e.g., "0%", "50%", "-20%"
    TTS_VOICE: "en-US-AnaNeural"  # Replace with your desired Azure voice
                                  # en-US-KaiNeural
                                  # en-US-Brian:DragonHDLatestNeural
                                  # en-US-Andrew2:DragonHDLatestNeural
                                  # en-US-AmberNeural ....(child)
                                  # en-US-AnaNeural ....(child)
    SPEECH_SYNTHESIS_RATE: "0%"  # Percentage or numerical value
    AUDIO_FORMAT: "Raw24Khz16BitMonoPcm"  # Mapping playback and format below
    AUDIO_FORMAT_RATES:
      Raw8Khz16BitMonoPcm: 8000
      Raw16Khz16BitMonoPcm: 16000
      Raw24Khz16BitMonoPcm: 24000
      Raw44100Hz16BitMonoPcm: 44100
      Raw48Khz16BitMonoPcm: 48000
    PLAYBACK_RATE: 24000  # Default playback rate
    ENABLE_PROFANITY_FILTER: false
    STABILITY: 0
    PROSODY:
      rate: "1.0"      # Adjust as needed, e.g., "1.0", "slow", "fast"
      pitch: "0%"      # Adjust as needed, e.g., "+10%", "-5%"
      volume: "default"  # Adjust as needed, e.g., "loud", "soft"

LLM_MODEL_CONFIG:
  OPENAI:
    RESPONSE_MODEL: "gpt-4o-mini"
    TEMPERATURE: 1.0
    TOP_P: 1.0
    N: 1
    SYSTEM_PROMPT_CONTENT: "You are a helpful but witty and dry assistant"
    STREAM_OPTIONS:
      include_usage: true
    STOP: null
    MAX_TOKENS: null
    PRESENCE_PENALTY: 0.0
    FREQUENCY_PENALTY: 0.0
    LOGIT_BIAS: null
    USER: null
    TOOLS: null
    TOOL_CHOICE: null
    MODALITIES:
      - text

  ANTHROPIC:
    RESPONSE_MODEL: "claude-3-5-haiku-20241022"
    TEMPERATURE: 1
    TOP_P: 1
    SYSTEM_PROMPT: "you are a dry and witty assistant"
    MAX_TOKENS: 1024
    STOP_SEQUENCES: null
    STREAM_OPTIONS:
      include_usage: true

  GEMINI:
    MODEL_VERSION: "gemini-1.5-flash"  # Specify the desired Gemini model version
    TEMPERATURE: 0.7  # Adjust the temperature for response randomness
    SYSTEM_PROMPT: "You are a knowledgeable assistant."  # Define the system instruction
    MAX_OUTPUT_TOKENS: 150  # Set the maximum number of tokens for the response
    TOP_P: 0.9  # Adjust the nucleus sampling parameter
    CANDIDATE_COUNT: 1  # Number of response candidates to generate

AUDIO_PLAYBACK_CONFIG:
  FORMAT: 16  # Bits per sample, typically 8 or 16 for PCM
  CHANNELS: 1  # 1 (mono), 2 (stereo)
  RATE: null  # Dynamically set at runtime based on TTS_PROVIDER


