GENERAL_TTS:
  TTS_PROVIDER: "openai"  # Possible values: "openai", "azure"

PROCESSING_PIPELINE:

  USE_SEGMENTATION: false # (global setting) Set to false to turn off segmentation during streaming
  DELIMITERS: ["\n"]  # Delimiters used for segmentation, eg., ". ", "? ", "! "
  NLP_MODULE: "none"  # Specify the NLP module, e.g., "nltk", "stanza", "spacy", "none"

TTS_MODELS:
  # OpenAI TTS Configuration
  OPENAI_TTS:
    TTS_CHUNK_SIZE: 1024
    TTS_SPEED: 1.0  # Possible values: 0.5 (slower) to 2.0 (faster); 1.0 is standard speed
    TTS_VOICE: "alloy"  # Possible values: alloy, echo, fable, onyx, nova, and shimmer
    TTS_MODEL: "tts-1"  # Possible values: model-specific, e.g., "tts-1", "tts-2"
    AUDIO_RESPONSE_FORMAT: "pcm"  # Possible values: "pcm" (default), "mp3", "wav"; audio encoding formats
    AUDIO_FORMAT_RATES:
      pcm: 24000  # Sample rate for PCM audio
      mp3: 44100  # Sample rate for MP3 audio
      wav: 48000  # Sample rate for WAV audio
    PLAYBACK_RATE: 24000  # Default sample rate for OpenAI audio playback

  # Azure TTS Configuration
  AZURE_TTS:
    TTS_SPEED: "0%"  # Can be percentage or numerical value; e.g., "0%", "50%", "-20%"
    TTS_VOICE: "en-US-KaiNeural"  # Replace with your desired Azure voice
                                  # en-US-KaiNeural
                                  # en-US-Brian:DragonHDLatestNeural
                                  # en-US-Andrew2:DragonHDLatestNeural
                                  # en-US-AmberNeural ....(child)
                                  # en-US-AnaNeural ....(child)
    SPEECH_SYNTHESIS_RATE: "0%"  # Percentage or numerical value
    AUDIO_FORMAT: "Raw24Khz16BitMonoPcm"  # Mapping playback and format below
    AUDIO_FORMAT_RATES:
      Raw8Khz16BitMonoPcm: 8000
      Raw16Khz16BitMonoPcm: 16000
      Raw24Khz16BitMonoPcm: 24000
      Raw44100Hz16BitMonoPcm: 44100
      Raw48Khz16BitMonoPcm: 48000
    PLAYBACK_RATE: 24000  # Default playback rate
    ENABLE_PROFANITY_FILTER: false
    STABILITY: 0
    PROSODY:
      rate: "1.0"      # Adjust as needed, e.g., "1.0", "slow", "fast"
      pitch: "0%"      # Adjust as needed, e.g., "+10%", "-5%"
      volume: "default"  # Adjust as needed, e.g., "loud", "soft"


AUDIO_PLAYBACK_CONFIG:
  FORMAT: 16  # Bits per sample, typically 8 or 16 for PCM
  CHANNELS: 1  # 1 (mono), 2 (stereo)
  RATE: null  # Dynamically set at runtime based on TTS_PROVIDER


