GENERAL_TTS:
  TTS_PROVIDER: "azure"  # Possible values: "openai", "azure"
  DELIMITERS: [". ", "? ", "! "]  # Relevant for upstream text segmentation
  MINIMUM_PHRASE_LENGTH: 25  # Minimum length for a phrase before splitting

TTS_MODELS:
  OPENAI_TTS:
    TTS_CHUNK_SIZE: 1024
    TTS_SPEED: 1.0  # Possible values: 0.5 (slower) to 2.0 (faster); 1.0 is standard speed
    TTS_VOICE: "alloy"  # Possible values: alloy, echo, fable, onyx, nova, and shimmer.
    TTS_MODEL: "tts-1"  # Possible values: model-specific, e.g., "tts-1", "tts-2"
    AUDIO_RESPONSE_FORMAT: "pcm"  # Possible values: "pcm" (default), "mp3", "wav"; audio encoding formats
    PLAYBACK_RATE: 24000  # Sample rate for OpenAI audio playback

  AZURE_TTS:
    TTS_SPEED: "0%"  # Can be percentage or numerical value; e.g., "0%", "50%", "-20%"
    TTS_VOICE: "en-US-KaiNeural"  # Replace with your desired Azure voice
    SPEECH_SYNTHESIS_RATE: "0%"  # Percentage or numerical value
    AUDIO_FORMAT: "Raw24Khz16BitMonoPcm"  # Supported Azure formats:
                                          # raw-8khz-16bit-mono-pcm  -> Raw8Khz16BitMonoPcm
                                          # raw-16khz-16bit-mono-pcm -> Raw16Khz16BitMonoPcm
                                          # raw-24khz-16bit-mono-pcm -> Raw24Khz16BitMonoPcm
                                          # raw-44100hz-16bit-mono-pcm -> Raw44100Hz16BitMonoPcm
                                          # raw-48khz-16bit-mono-pcm -> Raw48Khz16BitMonoPcm
    PLAYBACK_RATE: 24000  # Ensure this matches the playback rate of the selected AUDIO_FORMAT
    ENABLE_PROFANITY_FILTER: false  # Optional: Enable or disable profanity filter
    STABILITY: 0  # Optional: Controls stability of neural voices

    PROSODY:
      rate: "1.0"      # Adjust as needed, e.g., "1.0", "slow", "fast"
      pitch: "0%"      # Adjust as needed, e.g., "+10%", "-5%"
      volume: "default"  # Adjust as needed, e.g., "loud", "soft"

LLM_MODEL_CONFIG:
  OPENAI:
    RESPONSE_MODEL: "gpt-4o-mini"
    TEMPERATURE: 1.0
    TOP_P: 1.0
    N: 1
    SYSTEM_PROMPT_CONTENT: "You are a helpful but witty and dry assistant"
    STREAM_OPTIONS:
      include_usage: true
    STOP: null
    MAX_TOKENS: null
    PRESENCE_PENALTY: 0.0
    FREQUENCY_PENALTY: 0.0
    LOGIT_BIAS: null
    USER: null
    TOOLS: null
    TOOL_CHOICE: null
    MODALITIES:
      - text

  ANTHROPIC:
    RESPONSE_MODEL: "claude-3-5-haiku-20241022"
    TEMPERATURE: 0.7
    TOP_P: 0.9
    SYSTEM_PROMPT: "you are a dry and witty assistant"
    MAX_TOKENS: 1024
    STOP_SEQUENCES: null
    STREAM_OPTIONS:
      include_usage: true

AUDIO_PLAYBACK_CONFIG:
  FORMAT: 16  # Possible values: integer (e.g., 8, 16, 32); represents bits per sample, typically 8 or 16 for PCM
  CHANNELS: 1  # Possible values: 1 (mono), 2 (stereo); sets audio channels
  RATE: null  # Dynamically set at runtime based on TTS_PROVIDER
