
PHRASE_PROCESSING_MODULE: "phrase_queue"  # Specify the default value or update as required


GENERAL_TTS:
  TTS_PROVIDER: "azure"  # Possible values: "openai", "azure"
  DELIMITERS: [". ", "? ", "! "]  # Add if intended to be part of GENERAL_TTS
  MINIMUM_PHRASE_LENGTH: 25  # Add if intended to be part of GENERAL_TTS

PROCESSING_PIPELINE:
  USE_PHRASE_SEGMENTATION: true  # Set to false to turn off segmentation during streaming
  DELIMITERS: [". ", "? ", "! "]  # If segmentation is used
  MINIMUM_PHRASE_LENGTH: 25  # If segmentation is used
  MODULES:  # List of modules to include in the pipeline
    - tokenizer
    - custom_text_modifier
  TOKENIZER:
    TYPE: "none"  # Options: "nltk", "stanza", "none"
  CUSTOM_TEXT_MODIFIER:
    ENABLED: false

TTS_MODELS:
  OPENAI_TTS:
    TTS_CHUNK_SIZE: 1024
    TTS_SPEED: 1.0  # Possible values: 0.5 (slower) to 2.0 (faster); 1.0 is standard speed
    TTS_VOICE: "alloy"  # Possible values: alloy, echo, fable, onyx, nova, and shimmer.
    TTS_MODEL: "tts-1"  # Possible values: model-specific, e.g., "tts-1", "tts-2"
    AUDIO_RESPONSE_FORMAT: "pcm"  # Possible values: "pcm" (default), "mp3", "wav"; audio encoding formats
    AUDIO_FORMAT_RATES:  # Define playback rates for each possible format dynamically
      pcm: 24000  # Sample rate for PCM audio
      mp3: 44100  # Sample rate for MP3 audio
      wav: 48000  # Sample rate for WAV audio
    PLAYBACK_RATE: 24000  # Default sample rate for OpenAI audio playback

  AZURE_TTS:
    TTS_SPEED: "0%"  # Can be percentage or numerical value; e.g., "0%", "50%", "-20%"
    TTS_VOICE: "en-US-KaiNeural"  # Replace with your desired Azure voice
    SPEECH_SYNTHESIS_RATE: "0%"  # Percentage or numerical value
    AUDIO_FORMAT: "Raw24Khz16BitMonoPcm"  # mapping playback and format below
    AUDIO_FORMAT_RATES:  # Define playback rates for each possible format dynamically
      Raw8Khz16BitMonoPcm: 8000  # Playback rate for Raw8Khz16BitMonoPcm
      Raw16Khz16BitMonoPcm: 16000  # Playback rate for Raw16Khz16BitMonoPcm
      Raw24Khz16BitMonoPcm: 24000  # Playback rate for Raw24Khz16BitMonoPcm
      Raw44100Hz16BitMonoPcm: 44100  # Playback rate for Raw44100Hz16BitMonoPcm
      Raw48Khz16BitMonoPcm: 48000  # Playback rate for Raw48Khz16BitMonoPcm
    PLAYBACK_RATE: 24000  # Default: Ensure this matches the playback rate of the selected AUDIO_FORMAT
    ENABLE_PROFANITY_FILTER: false  # Optional: Enable or disable profanity filter
    STABILITY: 0  # Optional: Controls stability of neural voices
    PROSODY:
      rate: "1.0"      # Adjust as needed, e.g., "1.0", "slow", "fast"
      pitch: "0%"      # Adjust as needed, e.g., "+10%", "-5%"
      volume: "default"  # Adjust as needed, e.g., "loud", "soft"


LLM_MODEL_CONFIG:
  OPENAI:
    RESPONSE_MODEL: "gpt-4o-mini"
    TEMPERATURE: 1.0
    TOP_P: 1.0
    N: 1
    SYSTEM_PROMPT_CONTENT: "You are a helpful but witty and dry assistant"
    STREAM_OPTIONS:
      include_usage: true
    STOP: null
    MAX_TOKENS: null
    PRESENCE_PENALTY: 0.0
    FREQUENCY_PENALTY: 0.0
    LOGIT_BIAS: null
    USER: null
    TOOLS: null
    TOOL_CHOICE: null
    MODALITIES:
      - text

  ANTHROPIC:
    RESPONSE_MODEL: "claude-3-5-haiku-20241022"
    TEMPERATURE: 0.7
    TOP_P: 0.9
    SYSTEM_PROMPT: "you are a dry and witty assistant"
    MAX_TOKENS: 1024
    STOP_SEQUENCES: null
    STREAM_OPTIONS:
      include_usage: true

AUDIO_PLAYBACK_CONFIG:
  FORMAT: 16  # Possible values: integer (e.g., 8, 16, 32); represents bits per sample, typically 8 or 16 for PCM
  CHANNELS: 1  # Possible values: 1 (mono), 2 (stereo); sets audio channels
  RATE: null  # Dynamically set at runtime based on TTS_PROVIDER

LOGGING:
  ENABLED: true  # Set to false to disable logging
  LEVEL: "INFO"  # Possible values: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"