version: 1
disable_existing_loggers: True

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    level: DEBUG
    filename: app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  backend:
    handlers: [console, file]
    level: DEBUG
    propagate: no

  backend.TTS:
    handlers: [console, file]
    level: DEBUG
    propagate: no

  backend.text_generation:
    handlers: [console, file]
    level: DEBUG
    propagate: no

  backend.audio_players:
    handlers: [console, file]
    level: DEBUG
    propagate: no

  backend.utils:
    handlers: [console, file]
    level: DEBUG
    propagate: no

  delimiters:
    handlers: [console, file]
    level: DEBUG
    propagate: no

root:
  handlers: [console, file]
  level: DEBUG
